<?php
/**
 * Portuguese Language File
 */
$lang = [
    // Geral
    'app_name' => 'Banco Mercantil',
    'welcome' => 'Bem-vindo',
    'login' => 'Iniciar Sessão',
    'logout' => 'Sair',
    'save' => 'Salvar',
    'cancel' => 'Cancelar',
    'edit' => 'Editar',
    'delete' => 'Excluir',
    'search' => 'Pesquisar',
    'back' => 'Voltar',
    'actions' => 'Ações',
    'confirm' => 'Confirmar',
    'success' => 'Sucesso',
    'error' => 'Erro',
    'warning' => 'Aviso',
    'info' => 'Informação',
    
    // Login
    'login' => 'Iniciar Sessão',
    'login_button_text' => 'Entrar',
    'username' => 'Usuário',
    'password' => 'Senha',
    'forgot_password' => 'Esqueceu sua senha?',
    'fill_all_fields' => 'Por favor, preencha todos os campos.',
    'username_placeholder' => 'Digite seu usuário...',
    'password_placeholder' => 'Digite sua senha...',
    
    // Dashboard
    'dashboard' => 'Painel',
    'clients' => 'Clientes',
    'accounts' => 'Contas',
    'transactions' => 'Transações',
    'reports' => 'Relatórios',
    'branches' => 'Agências',
    'total_clients' => 'Total de clientes',
    'total_accounts' => 'Total de contas',
    'today_transactions' => 'Transações hoje',
    'recent_transactions' => 'Transações Recentes',
    
    // Clientes
    'new_client' => 'Novo Cliente',
    'client_list' => 'Lista de Clientes',
    'name' => 'Nome',
    'last_name' => 'Sobrenome',
    'maternal_last_name' => 'Sobrenome Materno',
    'paternal_last_name' => 'Sobrenome Paterno',
    'id_number' => 'Cédula de Identidade',
    'address' => 'Endereço',
    'phone' => 'Telefone',
    'email' => 'E-mail',
    'birth_date' => 'Data de Nascimento',
    'client_details' => 'Detalhes do Cliente',
    'client_saved' => 'Cliente salvo com sucesso',
    'client_updated' => 'Cliente atualizado com sucesso',
    'client_deleted' => 'Cliente excluído com sucesso',
    
    // Contas
    'new_account' => 'Nova Conta',
    'account_list' => 'Lista de Contas',
    'account_number' => 'Número da Conta',
    'account_type' => 'Tipo de Conta',
    'savings_account' => 'Conta Poupança',
    'checking_account' => 'Conta Corrente',
    'currency' => 'Moeda',
    'bolivianos' => 'Bolivianos',
    'dollars' => 'Dólares',
    'balance' => 'Saldo',
    'opening_date' => 'Data de Abertura',
    'status' => 'Estado',
    'active' => 'Ativa',
    'inactive' => 'Inativa',
    'account_details' => 'Detalhes da Conta',
    'account_saved' => 'Conta salva com sucesso',
    'account_updated' => 'Conta atualizada com sucesso',
    'account_deleted' => 'Conta excluída com sucesso',
    'select_client' => 'Selecionar Cliente',
    
    // Transações
    'new_transaction' => 'Nova Transação',
    'transaction_list' => 'Lista de Transações',
    'transaction_id' => 'ID da Transação',
    'transaction_type' => 'Tipo de Transação',
    'deposit' => 'Depósito',
    'withdrawal' => 'Saque',
    'amount' => 'Valor',
    'date' => 'Data',
    'time' => 'Hora',
    'description' => 'Descrição',
    'transaction_details' => 'Detalhes da Transação',
    'transaction_saved' => 'Transação realizada com sucesso',
    'insufficient_funds' => 'Fundos insuficientes para realizar esta operação',
    'select_account' => 'Selecionar Conta',
    'transaction_history' => 'Histórico de Transações',
    'start_date' => 'Data Inicial',
    'end_date' => 'Data Final',
    'generate_report' => 'Gerar Relatório',
    'print' => 'Imprimir',
    
    // Agências
    'new_office' => 'Nova Agência',
    'office_list' => 'Lista de Agências',
    'office_id' => 'ID da Agência',
    'office_name' => 'Nome da Agência',
    'central_office' => 'Agência Central',
    'branch_office' => 'Agência',
    'office_details' => 'Detalhes da Agência',
    'office_saved' => 'Agência salva com sucesso',
    'office_updated' => 'Agência atualizada com sucesso',
    'office_deleted' => 'Agência excluída com sucesso',
    
    // ATM
    'atm' => 'Caixa Eletrônico',
    'atm_id' => 'ID do Caixa',
    'location' => 'Localização',
    'atm_transaction' => 'Transação no Caixa',
    
    // Cartões
    'cards' => 'Cartões',
    'card_number' => 'Número do Cartão',
    'expiration_date' => 'Data de Expiração',
    'cvv' => 'CVV',
    'pin' => 'PIN',
    
    // Erros
    'page_not_found' => 'Página não encontrada',
    'access_denied' => 'Acesso negado',
    'session_expired' => 'Sua sessão expirou, por favor faça login novamente',
    'system_error' => 'Erro no sistema, por favor tente novamente mais tarde',
    
    // Relatórios
    'reports' => 'Relatórios',
    'transactions_by_date' => 'Transações por Data',
    'transactions_by_date_desc' => 'Relatório de todas as transações realizadas em um intervalo de datas específico.',
    'transactions_by_client' => 'Transações por Cliente',
    'transactions_by_client_desc' => 'Relatório de todas as transações realizadas por um cliente específico.',
    'atm_statistics' => 'Estatísticas de ATM',
    'atm_statistics_desc' => 'Relatório de estatísticas de uso de caixas eletrônicos.',
    'balances_by_branch' => 'Saldos por Agência',
    'balances_by_branch_desc' => 'Relatório de saldos totais administrados por cada agência.',
    'search_criteria' => 'Critérios de Pesquisa',
    'select_client' => 'Selecionar Cliente',
    'select_atm' => 'Selecionar ATM',
    'select_option' => 'Selecione uma opção',
    'generate_report' => 'Gerar Relatório',
    'view_report' => 'Ver Relatório',
    'results' => 'Resultados',
    'print' => 'Imprimir',
    'close' => 'Fechar',
    'period' => 'Período',
    'total_transactions' => 'Total de Transações',
    'total_deposits' => 'Total de Depósitos',
    'total_withdrawals' => 'Total de Saques',
    'no_transactions_found' => 'Nenhuma transação encontrada para os critérios selecionados.',
    'withdrawals' => 'Saques',
    'deposits' => 'Depósitos',
    'withdrawal_amount' => 'Valor de Saques',
    'deposit_amount' => 'Valor de Depósitos',
    'totals' => 'Totais',
    'clients_and_accounts_by_branch' => 'Clientes e Contas por Agência',
    'view' => 'Ver',
    'no_transactions' => 'Nenhuma transação recente.'
];
?>